service: function-compiled-with-babel

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  babelPresets:
    - latest

plugins:
  - serverless-babel-plugin

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
